sonar.projectKey=payment-service
sonar.projectName=Payment Service
sonar.projectVersion=1.0

sonar.sources=src

sonar.exclusions=\
    **/node_modules/**, \
    **/*.test.js, \
    **/*.spec.js, \
    **/coverage/**, \
    **/dist/**, \
    **/.git/**

sonar.language=js
sonar.sourceEncoding=UTF-8
